name: "PHPUnit tests"

on:
    pull_request:
        paths:
            - "**.php"
            - "phpunit.xml.dist"
            - ".github/workflows/phpunit.yaml"
    push:
        paths:
            - "**.php"
            - "phpunit.xml.dist"
            - ".github/workflows/phpunit.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
    unit-tests:
        name: PHPUnit L${{ matrix.laravel-version }}P${{ matrix.php-version }}-C${{ matrix.composer-prefer }}
        timeout-minutes: 5
        strategy:
            matrix:
                os: [ubuntu-latest]
                laravel-version: ["^8.0","^9.0","10.x-dev"]
                php-version: ["8.0", "8.1", "8.2"]
                composer-prefer: ["","--prefer-lowest --prefer-stable"]
                coverage: [xdebug]
                phpunit-flags: ["--coverage-clover coverage.xml"]
                exclude:
                    -   laravel-version: "^8.0"
                        php-version: "8.1"
                    -   laravel-version: "^8.0"
                        php-version: "8.2"
                    -   laravel-version: "10.x-dev"
                        php-version: "8.0"
                    -   laravel-version: "10.x-dev"
                        composer-prefer: "--prefer-lowest --prefer-stable"
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: ${{ matrix.coverage }}

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-Ver-L${{ matrix.laravel-version }}P${{ matrix.php-version }}-C${{ matrix.composer-prefer }}-${{ hashFiles('**/composer.json') }}
                    restore-keys: |
                        ${{ runner.os }}-Ver-L${{ matrix.laravel-version }}P${{ matrix.php-version }}-C${{ matrix.composer-prefer }}-
                        ${{ runner.os }}-Ver-L${{ matrix.laravel-version }}P${{ matrix.php-version }}-
                        ${{ runner.os }}-Ver-L${{ matrix.laravel-version }}

            -   name: Install dependencies
                run: composer update --prefer-dist --no-progress --ignore-platform-req="ext-*" --with laravel/framework:${{ matrix.laravel-version }} ${{ matrix.composer-prefer }}

            -   name: Check platform requirements
                run: composer check-platform-reqs

            -   name: List environment
                env:
                    GITHUB_CONTEXT: ${{ toJSON(github) }}
                    JOB_CONTEXT: ${{ toJSON(job) }}
                    STEPS_CONTEXT: ${{ toJSON(steps) }}
                    RUNNER_CONTEXT: ${{ toJSON(runner) }}
                    STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
                    MATRIX_CONTEXT: ${{ toJSON(matrix) }}
                run: |
                    composer show
                    env

            -   name: Run test suite
                run: vendor/bin/phpunit ${{ matrix.phpunit-flags }}

            -   name: Upload PHPunit coverage
                uses: codecov/codecov-action@v2
                with:
                    fail_ci_if_error: true # optional (default = false)
                    verbose: true # optional (default = false)
                    flags: unittests