name: "PHPUnit tests"

on:
    pull_request:
        paths:
            - "**.php"
            - "phpunit.xml.dist"
            - ".github/workflows/phpunit.yaml"
    push:
        paths:
            - "**.php"
            - "phpunit.xml.dist"
            - ".github/workflows/phpunit.yaml"

concurrency:
  group: unittests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
    unit-tests:
        name: PHPUnit Lar ${{ matrix.laravel-version }} PHP ${{ matrix.php-version }} Ver ${{ matrix.composer-prefer }}
        runs-on: ubuntu-latest
        timeout-minutes: 5
        strategy:
            matrix:
                laravel-php-version:
                    -   "^8.0,7.4"
                    -   "^8.0,8.0"
                    -   "^8.0,8.1"
                    -   "^9.0,8.0"
                    -   "^9.0,8.1"
                    -   "^9.0,8.2"
                    -   "^10.0,8.1"
                    -   "^10.0,8.2"
                composer-prefer:
                    -   ""
                    -   "--prefer-lowest --prefer-stable"
                coverage:
                    -   xdebug
                phpunit-flags:
                    -   '--coverage-clover coverage.xml'
                include:
                    -   laravel-php-version: "^8.0,7.4"
                        laravel-version: "^8.0"
                        php-version: "7.4"
                    -   laravel-php-version: "^8.0,8.0"
                        laravel-version: "^8.0"
                        php-version: "8.0"
                    -   laravel-php-version: "^8.0,8.1"
                        laravel-version: "^8.0"
                        php-version: "8.1"
                    -   laravel-php-version: "^9.0,8.0"
                        laravel-version: "^9.0"
                        php-version: "8.0"
                    -   laravel-php-version: "^9.0,8.1"
                        laravel-version: "^9.0"
                        php-version: "8.1"
                    -   laravel-php-version: "^9.0,8.2"
                        laravel-version: "^9.0"
                        php-version: "8.2"
                    -   laravel-php-version: "^10.0,8.1"
                        laravel-version: "^10.0"
                        php-version: "8.1"
                    -   laravel-php-version: "^10.0,8.2"
                        laravel-version: "^10.0"
                        php-version: "8.2"
        steps:
            -   name: Checkout
                uses: actions/checkout@master

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: ${{ matrix.coverage }}

            -   name: Validate composer.json and composer.lock
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-PHP-${{ matrix.php-version }}-Laravel-${{ matrix.laravel-version }}-prefer-${{ matrix.composer-prefer }}-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-PHP-${{ matrix.php-version }}-Laravel-${{ matrix.laravel-version }}-prefer-${{ matrix.composer-prefer }}-
                        ${{ runner.os }}-PHP-${{ matrix.php-version }}-Laravel-${{ matrix.laravel-version }}-
                        ${{ runner.os }}-PHP-${{ matrix.php-version }}-

            -   name: Require Laravel Framework ${{ matrix.laravel-version}}
                run: composer require laravel/framework:${{ matrix.laravel-version }} ${{ matrix.composer-prefer }}

            -   name: Install dependencies
                run: composer update --prefer-dist --no-progress --ignore-platform-req="ext-*" ${{ matrix.composer-prefer }}

            -   name: Check platform requirements
                run: composer check-platform-reqs

            -   name: List environment
                env:
                    GITHUB_CONTEXT: ${{ toJSON(github) }}
                    JOB_CONTEXT: ${{ toJSON(job) }}
                    STEPS_CONTEXT: ${{ toJSON(steps) }}
                    RUNNER_CONTEXT: ${{ toJSON(runner) }}
                    STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
                    MATRIX_CONTEXT: ${{ toJSON(matrix) }}
                run: |
                    composer show
                    env

            -   name: Run test suite
                run: vendor/bin/phpunit ${{ matrix.phpunit-flags }}

            -   name: Upload PHPunit coverage
                uses: codecov/codecov-action@v2
                with:
                    fail_ci_if_error: true # optional (default = false)
                    verbose: true # optional (default = false)
                    flags: unittests